
name: weather_app
description: Weather App

publish_to: 'none' 

version: 1.2.0


environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  json_annotation: ^4.8.1
  logger: ^2.0.2
  flutter_bmflocation: ^3.4.1
  flutter_baidu_mapapi_base: ^3.4.1
  google_mobile_ads: ^3.0.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
